### ISSUE TITLE
Docs are pointing back at itertools

### ISSUE THREAD

**Issue by ghost** [bluss/itertools-num#1]
The README cargo info and docs link both point toward itertools, but this looks like a different crate.

**Comment by bluss** [comment]
Thanks, yeah, this crate has barely left the starting line

**Comment by ghost** [comment]
Already in my project's dev-dependencies, sorry 😉

**Comment by bluss** [comment]
It's fixed now.

**Comment by bluss** [comment]
You're welcome to adopt this crate, if you have ideas for it.

**Comment by ghost** [comment]
I have ideas, but I'm not capable enough with Rust to produce broad library-quality code yet.
